# !!!
# ( !! WARNING !!) this config file is prepared ONLY for debugging...
# !!!

install_path: /usr/local/torigoya
workspace_path: "/tmp"
package_scripts_path: "%{_home}/../torigoya_package_scripts"
placeholder_path: "%{_home}/../placeholder"
apt_repository_path: "%{_home}/../apt_repository"
target_system: "x86_64-linux-gnu"
target_arch: "amd64"

# pass: test
admin_pass_sha512: "ee26b0dd4af7e749aa1a8ee3c10ae9923f618980772e473f8819a5d4940e0db27ac185f8a0e1d5f84f88bc887fd67b143732c304cc5fa9ad8e6f57f50028a8ff"
session_secret: "saltsalt"
